#### Loading notebook
##### CO use only

In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

import numpy as np
import pandas as pd
import os

import glob
import re
from datetime import datetime
import sys
from pathlib import Path
from typing import Union, Dict, List, Optional, Tuple

from aind_dynamic_foraging_data_utils import nwb_utils as nu
import aind_dynamic_foraging_basic_analysis.licks.annotation as a

sys.path.insert(1, '/root/capsule/src/utils')
import behavior_utils as bu
import array_utils as au
import load_utils as lu

ModuleNotFoundError: No module named 'behavior_utils'

##### nwb foraging bonsai to CSV

In [ ]:
# Set directory for nwbs to process
base_dir='/root/capsule/data/foraging_nwb_bonsai'

In [ ]:
# Load nwbs from base directory with filenames matching valid regex patterns 
# Returns csv files into scratch folder (default)
lu.load_nwb_files(base_dir = basedir)

In [23]:
# Set source path for combined Pandas DataFrame creation
source_path = '/root/capsule/scratch'

# Create concatenated DataFrame using CSV files in source path
# Add subject_id and session_date categorical columns based on filename
processed_nwb_df = lu.process_csv_files(source_path)
print(processed_nwb_df.shape)

Could not extract metadata from 0_2024-11-21.csv
Could not extract metadata from 1_2024-09-30.csv
Could not extract metadata from 45678_2024-09-11.csv
Could not extract metadata from 1_2024-04-13.csv
Could not extract metadata from 1_2024-09-16.csv
Could not extract metadata from 3_2024-09-23.csv
Could not extract metadata from 23456789_2024-10-31.csv
Could not extract metadata from 324567890_2024-10-31.csv
Could not extract metadata from 3_2024-10-21.csv
Could not extract metadata from 5_2024-09-09.csv
Could not extract metadata from 0_2024-12-04.csv
Could not extract metadata from 2_2024-08-14.csv
Could not extract metadata from 2_2024-08-05.csv
Could not extract metadata from 324567890_2024-11-01.csv
Could not extract metadata from 1_2024-04-19.csv
Could not extract metadata from 3_2024-10-07.csv
Could not extract metadata from 1_2024-04-06.csv
Could not extract metadata from 1_2024-08-19.csv
Could not extract metadata from 2345678_2024-11-01.csv
Could not extract metadata from 0_2024-11-22.csv
Could not extract metadata from 4_2024-09-09.csv
Could not extract metadata from 3_2024-11-18.csv
Could not extract metadata from 05_2023-11-08.csv
Could not extract metadata from 11_2024-08-13.csv
Could not extract metadata from 1_2024-08-05.csv
Could not extract metadata from 3_2024-08-30.csv
Could not extract metadata from 2_2024-09-30.csv
Could not extract metadata from 1_2024-08-14.csv
Could not extract metadata from 4_2024-10-14.csv
Could not extract metadata from 2_2024-10-07.csv
Could not extract metadata from 1_2024-11-25.csv
Could not extract metadata from 4_2024-09-23.csv
Could not extract metadata from 1_2024-08-09.csv
Could not extract metadata from 1_2024-09-17.csv
Could not extract metadata from 6_2024-09-09.csv
Could not extract metadata from 0_2024-11-15.csv
Could not extract metadata from 1_2024-08-30.csv
Could not extract metadata from 0_2024-11-19.csv
Could not extract metadata from 23456789_2024-10-25.csv
Could not extract metadata from 3_2024-08-09.csv
Could not extract metadata from 2_2024-08-19.csv
Could not extract metadata from 8_2024-11-19.csv

,trial,animal_response,rewarded_historyL,rewarded_historyR,bait_left,bait_right,base_reward_probability_sum,reward_probabilityL,reward_probabilityR,reward_random_number_left,...,reward_time_in_session,reward_time_in_trial,choice_time_in_session,choice_time_in_trial,earned_reward,extra_reward,subject_id,session_date,reward_delay,minimum_opto_interval
0,0,2.0,False,False,False,False,0.45,0.4,0.05,0.789076,...,NaN,NaN,NaN,NaN,False,False,687553,2023-12-01,NaN,NaN
1,1,2.0,False,False,False,False,0.45,0.4,0.05,0.518192,...,NaN,NaN,NaN,NaN,False,False,687553,2023-12-01,NaN,NaN
2,2,0.0,True,False,True,False,0.45,0.4,0.05,0.367511,...,16.160096,0.487072,16.153088,0.480064,True,False,687553,2023-12-01,NaN,NaN
3,3,0.0,True,False,True,False,0.45,0.4,0.05,0.053372,...,25.333088,0.376064,25.331872,0.374848,True,False,687553,2023-12-01,NaN,NaN
4,4,0.0,False,False,False,False,0.45,0.4,0.05,0.955191,...,NaN,NaN,34.364160,0.157440,False,False,687553,2023-12-01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2577768,582,1.0,False,False,False,False,0.45,0.4,0.05,0.700221,...,NaN,NaN,5378.042624,0.199680,False,False,724555,2024-07-10,0.0,0.0
2577769,583,2.0,False,False,False,False,0.45,0.4,0.05,0.678467,...,NaN,NaN,NaN,NaN,False,False,724555,2024-07-10,0.0,0.0
2577770,584,1.0,False,False,True,False,0.45,0.4,0.05,0.050451,...,NaN,NaN,5392.707232,0.347424,False,False,724555,2024-07-10,0.0,0.0
2577771,585,1.0,False,False,True,False,0.45,0.4,0.05,0.118763,...,NaN,NaN,5404.919264,0.359232,False,False,724555,2024-07-10,0.0,0.0
2577772,586,0.0,True,False,True,False,0.45,0.4,0.05,0.130339,...,5410.429088,0.219136,5410.427904,0.217952,True,False,724555,2024-07-10,0.0,0.0

In [24]:
# Set download location for combined DataFrame
filepath = '/root/capsule/data/file_process_output'

# Download DataFrame to selected filepath 
downloaded_path = lu.download_dataframe_to_csv(
    processed_nwb_df, 
    filepath=filepath, 
    filename='foraging_trials_bonsai.csv', 
    overwrite=True
)

In [2]:
# Check downloaded size 

file_size = os.path.getsize(filepath)
print("File size:", file_size, "bytes")

File size: 40 bytes